kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-roboshop
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0faf9ce59534689cb
  directoryPerms: "700"
  basePath: "/roboshop" # /roboshop/cart
